version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1-amd64
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticdata:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9200:9200"
#      - "9200"
#      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      elk:
        ipv4_address: 11.0.0.2
    restart: always


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      elk:
        ipv4_address: 11.0.0.3
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always


  logstash:
    build:
      context: logstash/
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    #      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      elk:
        ipv4_address: 11.0.0.5
#    ports:
#      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    restart: always


    #  metricbeat:
    #    build:
    #      context: metricbeat/
    #    networks:
    #      elk:
    #        ipv4_address: 11.0.0.6
    #    links:
    #      - elasticsearch
    #      - logstash
    #    depends_on:
    #      - logstash
    #    restart: always
    #    volumes:
    #      - /proc:/hostfs/proc:ro
    #      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    #      - /:/hostfs:ro


  filebeat:
    build:
      context: filebeat/
    networks:
      elk:
        ipv4_address: 11.0.0.7
    depends_on:
      - kibana
      - logstash
    links:
      - elasticsearch
      - kibana
      - logstash
    ports:
      - "8022:22"
    restart: always
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/filebeat:/run
#      - ./filebeat/auth.log:/var/log/secure


  nginx:
    build:
      context: nginx/
    ports:
      - "80:80"
    environment:
      - KIBANA_USERNAME="admin"
      - KIBANA_PASSWORD="admin_password"
    networks:
      elk:
        ipv4_address: 11.0.0.4
    depends_on:
      - kibana
      - elasticsearch
    restart: always
    extra_hosts:
      - "kibana.secop.edu:127.0.0.1"
      - "elastic.secop.edu:127.0.0.1"

volumes:
  elasticdata:
    driver: local

networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/24
