version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1-amd64
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      elk:
        ipv4_address: 11.0.0.2
    restart: always


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      elk:
        ipv4_address: 11.0.0.3
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: unless-stopped


  logstash:
    build:
      context: logstash/
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    #      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      elk:
        ipv4_address: 11.0.0.5
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: unless-stopped


  metricbeat:
    build:
      context: metricbeat/
    networks:
      elk:
        ipv4_address: 11.0.0.6
    links:
      - elasticsearch
      - logstash
      - kibana
      - nginx
    depends_on:
      - elasticsearch
    restart: unless-stopped
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/config/metricbeat.yml
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro


  filebeat:
    build:
      context: filebeat/
    networks:
      elk:
        ipv4_address: 11.0.0.7
    depends_on:
      - elasticsearch
      - logstash
    links:
      - elasticsearch
      - kibana
      - logstash
    ports:
      - "8022:22"
    restart: unless-stopped
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/auth.log:/var/log/secure:ro


  nginx:
    build:
      context: nginx/
    ports:
      - "80:80"
    environment:
      - KIBANA_USERNAME="admin"
      - KIBANA_PASSWORD="admin_password"
    networks:
      elk:
        ipv4_address: 11.0.0.4
    depends_on:
      - kibana
      - elasticsearch
    restart: unless-stopped
    extra_hosts:
      - "kibana.secop.edu:127.0.0.1"
      - "elastic.secop.edu:127.0.0.1"
      - "logstash.secop.edu:127.0.0.1"

volumes:
  elasticdata:
    driver: local

networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/24
