version: '3'

services:

  metricbeat:
    hostname: nemo-metricbeat
    build:
      context: AMD64/metricbeat
    networks:
      elk:
        ipv4_address: 11.0.0.6
    restart: unless-stopped
    volumes:
      - ./AMD64/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./AMD64/metricbeat/modules.d/system.yml:/usr/share/metricbeat/modules.d/system.yml
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock

  filebeat:
    hostname: nemo-filebeat
    build:
      context: AMD64/filebeat
    networks:
      elk:
        ipv4_address: 11.0.0.7
    restart: unless-stopped
    volumes:
      - /var/log/auth.log:/var/log/secure:ro

networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/24
