filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

filebeat.modules:
#  #---------------------------- Elasticsearch Module ----------------------------
  - module: elasticsearch
    # Server log
    server:
      enabled: true
#
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
#      #var.paths:
#
#    gc:
#      enabled: true
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
#      #var.paths:
#
#    audit:
#      enabled: true
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
#      #var.paths:
#
#    slowlog:
#      enabled: true
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
#      #var.paths:
#
#    deprecation:
#      enabled: true
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
#      #var.paths:
#
  - module: system
    syslog:
      enabled: true
#
#      # Set custom paths for the log files. If left empty,
#      # Filebeat will choose the paths depending on your OS.
      var.paths: [ "/var/log/secure" ]
#
#      # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
#      var.convert_timezone: true
#
#      # Authorization logs
      auth:
        enabled: true
#
#        # Set custom paths for the log files. If left empty,
#        # Filebeat will choose the paths depending on your OS.
#        var.paths: [ "/var/log/secure" ]
#
#        # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
#        var.convert_timezone: true
#
## =========================== Filebeat inputs =============================
#filebeat:
#  inputs:
#    - type: log
#      enabled: true
#      paths:
#        - /var/log/secure
#
##filebeat.inputs:
##  - input_type: log
##    paths:
##      - /var/log/secure
##
##document_type: sshd
##fields_under_root: true
#output.logstash:
#  hosts: [ "http://logstash:5044" ]
#
## ---------------------------- Elasticsearch Output ----------------------------
##output.elasticsearch:
##  hosts: [ "http://elasticsearch:9200" ]
##  username: "elastic"
##  password: "admin"
#
## =================================== Kibana ===================================
setup.kibana:
  host: "http://kibana:5601"

filebeat.inputs:
  - type: log
    paths:
      - "/var/log/secure"
    json.message_key: log
    json.keys_under_root: true
    processors:
      - add_docker_metadata: ~
output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
