#filebeat.config.modules:
#   enabled: true
#  path: /usr/share/filebeat/modules.d/*.yml


filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/secure
#      input_type: log
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after

processors:
    - timestamp:
        field: start_time
        timezone: 'Europe/London'
        layouts:
          - 'Mon, 02 Jan 98 15:04 WET'
        test:
          - 'Mon, 02 Jan 98 15:04 WET'
    - drop_fields:
        fields: [start_time]

output:
  logstash:
    hosts: ["logstash:5044"]

logging.level: debug
